FROM golang:alpine AS builder
WORKDIR /app
COPY proxy.go .
RUN go build -o proxy proxy.go

FROM alpine
RUN apk add --no-cache ca-certificates
COPY --from=builder /app/proxy /proxy
EXPOSE 18080
CMD ["/proxy"]