name: Tracker performance tests

on:
  workflow_call:
    inputs:
      runner-type:
        required: true
        type: string
        description: 'Runner type to use (e.g., ubuntu-24.04, buildjet-8vcpu-ubuntu-2204)'
  workflow_dispatch:
    inputs:
      runner-type:
        required: true
        type: choice
        description: 'Runner type to use'
        options:
          - ubuntu-24.04
          - buildjet-8vcpu-ubuntu-2204
        default: ubuntu-24.04

jobs:
  performance-tests:
    if: github.event_name == 'workflow_call' || github.actor == 'teleivo'
    runs-on: ${{ inputs.runner-type }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Start DHIS2
      run: |
        DHIS2_IMAGE=dhis2/core:42.0 \
        DHIS2_DB_DUMP_URL=https://databases.dhis2.org/sierra-leone/2.42.0/dhis2-db-sierra-leone.sql.gz \
        docker compose up -d

    - name: Wait for DHIS2 to be ready
      run: |
        echo "Waiting for DHIS2 to start..."
        timeout 300 bash -c 'until docker compose ps | grep -q "healthy"; do sleep 10; echo "Still waiting..."; done'
        echo "DHIS2 is ready!"

    - name: Run tracker performance tests
      run: |
        mvn clean gatling:test -Dgatling.simulationClass=org.hisp.dhis.test.TrackerExporterTests

    - name: Upload Gatling report
      if: always() # reports should always be uploaded as tests can fail due to our performance assertions
      uses: actions/upload-artifact@v4
      with:
        name: gatling-report-${{ runner.name }}-${{ github.run_id }}-${{ github.sha }}
        path: |
          target/gatling/
          !target/gatling/lastRun.txt

    - name: Cleanup
      if: always()
      run: docker compose down --volumes
