# https://docs.gatling.io/integrations/ci-cd/github-actions
name: Run Gatling Enterprise Simulation Using GHA

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Gatling Enterprise Action
        uses: gatling/enterprise-action@v1
        with:
          api_token: ${{ secrets.GATLING_ENTERPRISE_API_TOKEN }}
          # ../../.gatling/package.conf
          simulation_id: 162bed23-d64a-44d0-94f3-559da4bfb592
          extra_system_properties: >
            {
              "instance": "https://play.im.dhis2.org/stable-2-42-0"
            }
