name: Tracker Performance Tests

on:
  workflow_dispatch:
    branches: [ tracker-exporter-tests ]

jobs:
  performance-tests:
    # TODO try later
    # runs-on: buildjet-8vcpu-ubuntu-2204
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Start DHIS2 with Docker Compose
      run: |
        DHIS2_IMAGE=dhis2/core:42.0 \
        DHIS2_DB_DUMP_URL=https://databases.dhis2.org/sierra-leone/2.42.0/dhis2-db-sierra-leone.sql.gz \
        docker compose up -d

    - name: Wait for DHIS2 to be healthy
      run: |
        echo "Waiting for DHIS2 to start..."
        timeout 300 bash -c 'until docker compose ps | grep -q "healthy"; do sleep 10; echo "Still waiting..."; done'
        echo "DHIS2 is ready!"

    - name: Run Tracker Performance Tests
      run: |
        mvn clean gatling:test -Dgatling.simulationClass=org.hisp.dhis.test.TrackerExporterTests

    - name: Upload Gatling Reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: gatling-reports
        path: target/gatling/
        retention-days: 90

    - name: Cleanup
      if: always()
      run: docker compose down --volumes
